/**
 * Opens a print-ready popup for session plan PDF export.
 * Uses browser's native print-to-PDF — no backend dependency.
 */
export function exportSessionPlanPDF(plan, subjectName = '') {
    const p = plan.plan_data || {}
    const topic = p.topic || 'Session Plan'
    const date = plan.date || new Date().toISOString().split('T')[0]

    const concepts = (p.concepts || []).map(c => `
        <div class="concept-card">
            <h4>${c.name || ''}</h4>
            <p>${c.explanation || ''}</p>
            ${c.example ? `<div class="example"><strong>Example:</strong> ${c.example}</div>` : ''}
        </div>`).join('')

    const flow = (p.teaching_flow || []).map((step, i) => `
        <div class="flow-step">
            <span class="step-num">${i + 1}</span>
            <div><strong>${step.activity || ''}</strong> — ${step.duration || ''}<br/><span>${step.description || ''}</span></div>
        </div>`).join('')

    const misconceptions = (p.common_misconceptions || []).map(m => `
        <li><strong>${m.issue || m}</strong>${m.correction ? ` — ${m.correction}` : ''}</li>`).join('')

    const questions = (p.discussion_questions || []).map(q => `<li>${q}</li>`).join('')

    const summary = p.summary || ''
    const pref = plan.personalization_notes || p.personalization_notes || ''

    const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Session Plan — ${topic}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a2e; background: #fff; padding: 32px; font-size: 13px; line-height: 1.6; }
  .header { border-bottom: 3px solid #6366f1; padding-bottom: 16px; margin-bottom: 24px; }
  .header h1 { font-size: 22px; color: #6366f1; margin-bottom: 4px; }
  .header .meta { display: flex; gap: 24px; font-size: 12px; color: #555; margin-top: 8px; }
  .meta span { display: flex; align-items: center; gap: 4px; }
  h2 { font-size: 15px; color: #6366f1; border-bottom: 1px solid #e5e7eb; padding-bottom: 6px; margin: 20px 0 12px; }
  h3 { font-size: 13px; font-weight: 700; margin-bottom: 6px; }
  p, li { font-size: 13px; color: #333; }
  .concept-card { background: #f8f9ff; border: 1px solid #e0e0ff; border-radius: 6px; padding: 12px; margin-bottom: 10px; }
  .concept-card h4 { font-size: 13px; color: #4f46e5; margin-bottom: 4px; }
  .example { background: #fffbeb; border-left: 3px solid #f59e0b; padding: 6px 10px; margin-top: 6px; font-size: 12px; }
  .flow-step { display: flex; gap: 12px; align-items: flex-start; margin-bottom: 10px; }
  .step-num { background: #6366f1; color: #fff; border-radius: 50%; width: 24px; height: 24px; display: flex; align-items: center; justify-content: center; font-size: 12px; font-weight: 700; flex-shrink: 0; }
  .flow-step span { color: #555; font-size: 12px; }
  ul { padding-left: 20px; }
  li { margin-bottom: 6px; }
  .summary-box { background: #f0fdf4; border: 1px solid #86efac; border-radius: 6px; padding: 12px; }
  .pref-box { background: #faf5ff; border: 1px solid #d8b4fe; border-radius: 6px; padding: 12px; }
  .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #999; text-align: center; }
  @media print {
    body { padding: 16px; }
    .no-print { display: none !important; }
  }
</style>
</head>
<body>
<div class="header">
  <h1>📋 ${topic}</h1>
  <div class="meta">
    ${subjectName ? `<span>📚 ${subjectName}</span>` : ''}
    <span>📅 ${date}</span>
    ${p.duration_minutes ? `<span>⏱ ${p.duration_minutes} min</span>` : ''}
    ${p.difficulty_level ? `<span>📊 ${p.difficulty_level}</span>` : ''}
  </div>
</div>

${summary ? `<h2>Overview</h2><div class="summary-box"><p>${summary}</p></div>` : ''}

${concepts ? `<h2>Key Concepts</h2>${concepts}` : ''}

${flow ? `<h2>Teaching Flow</h2>${flow}` : ''}

${misconceptions ? `<h2>Common Misconceptions</h2><ul>${misconceptions}</ul>` : ''}

${questions ? `<h2>Discussion Questions</h2><ul>${questions}</ul>` : ''}

${pref ? `<h2>Personalisation Notes</h2><div class="pref-box"><p>${pref}</p></div>` : ''}

<div class="footer">Generated by AI Teacher Prep Portal — ${new Date().toLocaleString()}</div>

<div class="no-print" style="text-align:center;margin-top:24px;">
  <button onclick="window.print()" style="padding:10px 28px;background:#6366f1;color:#fff;border:none;border-radius:6px;font-size:14px;cursor:pointer;font-weight:600;">
    🖨️ Save / Print as PDF
  </button>
  <button onclick="window.close()" style="margin-left:12px;padding:10px 20px;background:#e5e7eb;color:#333;border:none;border-radius:6px;font-size:14px;cursor:pointer;">
    Close
  </button>
</div>
</body>
</html>`

    const win = window.open('', '_blank', 'width=900,height=700')
    if (win) {
        win.document.write(html)
        win.document.close()
    }
}

export function exportTermReportPDF(report, subjectName = '') {
    if (!report) return
    const headline = report.headline || ''
    const rating = report.overall_rating || ''
    const highlights = (report.highlights || []).map(h => `<li>${h}</li>`).join('')
    const improvements = (report.improvements || []).map(i => `<li>${i}</li>`).join('')
    const recommendations = (report.recommendations || []).map(r => `<li>${r}</li>`).join('')

    const unitSummaries = (report.unit_summaries || []).map(u => `
        <tr>
            <td>${u.unit || ''}</td>
            <td>${u.status || ''}</td>
            <td>${u.avg_score !== undefined ? u.avg_score + '%' : '—'}</td>
            <td>${u.sessions_count || '—'}</td>
        </tr>`).join('')

    const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Term Report — ${subjectName}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a2e; background: #fff; padding: 32px; font-size: 13px; line-height: 1.6; }
  .header { border-bottom: 3px solid #6366f1; padding-bottom: 16px; margin-bottom: 24px; }
  .header h1 { font-size: 22px; color: #6366f1; }
  .rating-badge { display:inline-block; background:#6366f1; color:#fff; padding:4px 14px; border-radius:20px; font-size:13px; font-weight:700; margin-top:8px; }
  h2 { font-size: 15px; color: #6366f1; border-bottom: 1px solid #e5e7eb; padding-bottom: 6px; margin: 20px 0 12px; }
  ul { padding-left: 20px; } li { margin-bottom: 6px; }
  table { width:100%; border-collapse:collapse; font-size:12px; }
  th { background:#6366f1; color:#fff; padding:8px 10px; text-align:left; }
  td { padding:7px 10px; border-bottom:1px solid #e5e7eb; }
  tr:nth-child(even) td { background:#f8f9ff; }
  .footer { margin-top:32px; padding-top:12px; border-top:1px solid #e5e7eb; font-size:11px; color:#999; text-align:center; }
  @media print { .no-print { display:none !important; } }
</style>
</head>
<body>
<div class="header">
  <h1>📋 Term Report — ${subjectName}</h1>
  <p style="margin-top:6px;color:#555">${headline}</p>
  ${rating ? `<div class="rating-badge">${rating}</div>` : ''}
</div>

${highlights ? `<h2>Highlights</h2><ul>${highlights}</ul>` : ''}
${improvements ? `<h2>Areas for Improvement</h2><ul>${improvements}</ul>` : ''}
${unitSummaries ? `<h2>Unit Breakdown</h2><table><thead><tr><th>Unit</th><th>Status</th><th>Avg Score</th><th>Sessions</th></tr></thead><tbody>${unitSummaries}</tbody></table>` : ''}
${recommendations ? `<h2>Recommendations</h2><ul>${recommendations}</ul>` : ''}

<div class="footer">Generated by AI Teacher Prep Portal — ${new Date().toLocaleString()}</div>
<div class="no-print" style="text-align:center;margin-top:24px;">
  <button onclick="window.print()" style="padding:10px 28px;background:#6366f1;color:#fff;border:none;border-radius:6px;font-size:14px;cursor:pointer;font-weight:600;">🖨️ Save / Print as PDF</button>
  <button onclick="window.close()" style="margin-left:12px;padding:10px 20px;background:#e5e7eb;color:#333;border:none;border-radius:6px;font-size:14px;cursor:pointer;">Close</button>
</div>
</body></html>`

    const win = window.open('', '_blank', 'width=900,height=700')
    if (win) { win.document.write(html); win.document.close() }
}
